### ISSUE TITLE
`parse_publication': `publication' must be of type `String' but `8080' is of type `Fixnum' (RuntimeError)

### ISSUE THREAD

**Issue by ooxi** [ooxi/mini-cross#14]
## Sample yaml

````yaml
---
base: ubuntu:16.04
install:
 - php-cli
publish:
 - 8080
---

````

## Exception

````
src/yaml/publish-instruction.rb:60:in `parse_publication': `publication' must be of type `String' but `8080' is of type `Fixnum' (RuntimeError)
````
